development:
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: nikhil
  database: bookworm_development
  host: localhost
  
test:
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: nikhil
  database: bookworm_test
  host: localhost

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: nikhil
  database: bookworm_production
  host: localhost
